server:
    port: 8081

spring:
    application:
        name: transaction-service
    data:
        mongodb:
            uri: ${MONGO_URL:mongodb://mongo:27017/fraudops}
    kafka:
        bootstrap-servers: ${KAFKA_BOOTSTRAP:kafka:9092}

management:
    endpoints:
        web:
            exposure:
                include: health, info, prometheus, metrics
    endpoint:
        health:
            show-details: always

logging:
    level:
        io.fraudops: DEBUG
